### PR TITLE
donation order changed for best donation count. error in reading donation text fixed

### PR DESCRIPTION
**Pull request by krendll**

### CODE REVIEW

**Comment by Blaze5145** [comment]
I think this should be made optional as many people prefer that their bot attack asap. Training bigger troops takes more time and hence will slow down the bot. Maybe we should have a poll about this in the forum. :)

**Comment by krendll** [comment]
It's just donation order, user can donate only archers( for example) for fast donation, but he can't donate smth more biggest without this patch. For example if request is "I need reinforcements" if user checked all units for donation - he will donate archers only and he can't donate giants. With patch he could select.
Maybe it should be selectable, such as "default order" or "from biggest to smallest", it is not to hard to code this option. Try create forum thread.

Commit 4aa272e fix critical error in main code, you should include it. As in fix use of length of array as string argument for detection.

**Comment by Blaze5145** [comment]
I think the array starting from 0 is right. Check it again ;) And you could've put seperate pull requests for the two. I wanted to pull in the donation order.

**Comment by krendll** [comment]
Yep, array should start from 0. BUT this array is created via function StringSplit, in code (readconfig.au3):
$aBlkBarbarians = StringSplit($sTxtBlackListBarbarians, @CRLF, $STR_ENTIRESPLIT)
and so on.....

And the function https://www.autoitscript.com/autoit3/docs/functions/StringSplit.htm
returns number of elements in zero element of array. 
"by default the first element ($aArray[0]) contains the number of strings returned,"

Either in readconfig.au3 should add $STR_NOCOUNT parameter to all readings of such strings, or much easy to change as i propose

You could easily check it, just add _ArrayDisplay($aBlackList) in CheckDonateTroop function

**Comment by Blaze5145** [comment]
Oh ok. A user just reported a bug based on this bug. Now I got it :) Please create a new thread under code snippets and take credit for your amazing discovery :)

**Comment by krendll** [comment]
Ok )))

**Comment by xtciaan** [comment]
How about... just add an extra setting under training tab... where the user
can customize the order whenever he wants?

Example.. next to all troops... is a dropdown... then you select 1,2,3 etc
etc?

**Comment by krendll** [comment]
It's possible, but i dont think it is really needed function.

**Pull request merged**
