### PR TITLE
Alpha Add Minimum Dark Elixir

### PR DESCRIPTION
**Pull request by IndraFer**
Add separate for Minimum Dark Elixir, so bot will check Meet Dark Elixir and Minimum Dark Elixir before cast spell in tow different ways :d hope i not forget edit anything

### CODE REVIEW

**Comment by Blaze5145** [comment]
Does this end the battle after zapping?

**Comment by IndraFer** [comment]
no, not add check to end battle after zapping

added back to All Base mode after x searches

here log:
2015-05-05 08:55:33 : ============== Searching For Dead Bases ==============
2015-05-05 08:55:33 : ~~~~~~~~~~~~~~~ SEARCH CONDITIONS ~~~~~~~~~~~~~~~~
2015-05-05 08:55:33 : Meet: Gold or Elixir, Dark
2015-05-05 08:55:33 : Meet One and Attack!
2015-05-05 08:55:33 : ~~~~~~~~~~~~~~ RESOURCE CONDITIONS ~~~~~~~~~~~~~~~
2015-05-05 08:55:33 : Aim: [G]:  80000 [E]:  80000 [D]: 1000 [T]: 0
2015-05-05 08:55:33 : ==================================================
2015-05-05 08:55:36 :   1> [G]:   5705 [E]:   7582 [D]:  245 [T]:23
2015-05-05 08:55:44 :   2> [G]: 301104 [E]: 301082 [D]: 1922 [T]:26
2015-05-05 08:55:49 : ~~~~~~~~~~~ Not a Dead Base, Skipping ~~~~~~~~~~~~
2015-05-05 08:55:52 :   3> [G]:   6030 [E]:  66022 [D]:    0 [T]: 2
2015-05-05 08:55:59 :   4> [G]:  19345 [E]:  11276 [D]:  265 [T]:28
2015-05-05 08:56:07 :   5> [G]: 253790 [E]: 327763 [D]: 1715 [T]:21
2015-05-05 08:56:13 :  Maximum Dead Base 1 Searches, Attacking All Base 
2015-05-05 08:56:13 : ================ Search Complete =================

**Comment by Blaze5145** [comment]
It says Maximum Dead Base 1 Searches but has searched 5?

**Comment by IndraFer** [comment]
it only will override atk only when not deadbase or weakbase found, so it don't override minimum G E or DE value compare (cause it will useless if bot atk empty base), but it use $iSkipped variable to check and bot still add $iSkipped when it skip G E DE value search.

**Comment by Blaze5145** [comment]
Oh so it displays the number of bases skipped[because not dead] but satisfying the loot requirements? Then I think that log message should go right after skipping that one dead base.

**Comment by IndraFer** [comment]
yes, i can add some notification after bot skip deadbase or weakbase, wait still testing :)

**Comment by IndraFer** [comment]
done, log include in last commit

**Pull request merged**
