### PR TITLE
add _PushImage function

### PR DESCRIPTION
**Pull request by batrako**
new _PushImage function in order to send Loot images in future. Also create /bin folder to store curl utility used by _PushImage function to bypass multipart/form-data encoding required byAPI. Maybe in future we can use curLib as dll instead.

### CODE REVIEW

**Comment by krendll** [comment]
Does it really needs curl? Autoit should have built-in functions to make post request without curl

**Comment by batrako** [comment]
Autoit simple POST request is easy. Upload process with pushbullet API is complex because require  multipart/form-data encoding. Curl helps you to send this muiltipart binary file with -F @file option with simple line. Official pushbullet API sample doc sample with it (https://docs.pushbullet.com/#upload-request). I tried  with Autoit,  requesting a simple POST with encondig "application/x-www-form-urlencoded" but API not recognize it correctly . I think that using curLib dll is more clean. I wil try it.

**Comment by krendll** [comment]
I just don't like use external libs ))) Paste you code for sending images to pushbullet without curl, i'll try to fix it.

**Comment by batrako** [comment]
Ok. Don't worry i will try to review and make some test in order to replace curl.exe utility by raw multipart/form-data function.

**Comment by Blaze5145** [comment]
And once you're done with it, create a PR into alpha not the master. Closing PR for now.

**Pull request closed without merging**
