### PR TITLE
Alpha

### PR DESCRIPTION
**Pull request by zyda**
Add loot/logs/debug file rotator handler and initial porting of pb remote from borken_bot

### CODE REVIEW

**Comment by Blaze5145** [comment]
Can you please describe each of the two features in detail? Thanks :)

**Comment by zyda** [comment]
Hi Blaze5145, Yap, will update the commit msg and send a version 2

HI krendll,
$dir_list[3] should be local variable as it is not used elsewhere.

Rotator file limit (100) should be taken from user input but I am not familiar with the GUI design so have not touch it. 

Do you have a suggestion where i should put the loot_log_cleanup function to?

I have only tested a basic feature, pause and resume, it works for me.

**Comment by krendll** [comment]
Zyda, you could make log_rotator as separate file with separate function.

 As for the local var you are wrong, because dirs could change or even add (i want to add function for screenshots for example) and your code would not work.

Now they are declared in "CGB Global Variables.au3"
i think you should add your debug dir here 
Global $dirLogs = @ScriptDir & "\logs\"
Global $dirLoots = @ScriptDir & "\Loots\"

maybe as separate array such as "rotator_array" for example
Second question - what is debug dir for ?

**Comment by zyda** [comment]
krendll, you are right, if the logs and loots path should be global. I will make the change. Rotator_array sounds good to me, I assuming making it as global variable.

The debug dir is used to store debug log file and screen captures. I will remove the debug first

**Comment by zyda** [comment]
i am close this and will make another pull request later next week

**Pull request closed without merging**
